name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
    - feature*
pr:
  branches:
    include:
    - master
    - release*
    - feature*

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

resources:
- repo: self
  clean: true

stages:
- stage: build
  jobs:
  - job: build

  #container: flatpak/flatpak-builder:freedesktop-1-6

    pool:
      vmImage: ubuntu-18.04

    displayName: Build

    steps:
    - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhmmss"))"
      displayName: Set Build Name for Non-PR
      condition: ne(variables['Build.Reason'], 'PullRequest')

    - pwsh: |
        ./build.ps1 -Bootstrap
      displayName: Bootstrap build

    - pwsh: |
        Get-ChildItem -Path env:
      displayName: Capture Environment

    - pwsh: |
        ./build.ps1 -Build
      displayName: build flatpak

